spring:
  application:
    name: money-transfer-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/money_transfer
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
    enabled: true

server:
  port: 8082

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

currency:
  converter:
    service:
      url: localhost:8083

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
