spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: postgres
    password: root

server:
  port: 8081

currency:
  converter:
    service:
      url: http://localhost:8083

ngrok:
  tunnel-url: http://localhost:8081